name: thtc-maps
services:
  # db:
  #   image: postgis/postgis:17-3.5-alpine
  #   restart: always
  #   expose:
  #     - 5432
  #   networks:
  #     - webnet
  #   environment:
  #     - POSTGRES_DB=db
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password
  #   volumes:
  #     # persist PostgreSQL data in a local directory outside of the docker container
  #     - ./pg_data:/var/lib/postgresql/data

  martin:
    image: ghcr.io/maplibre/martin:latest
    restart: always
    expose:
      - 3000
    deploy:
      replicas: 1
    networks:
      - webnet
    volumes:
      - ./martin:/data
    command: ["--config", "/data/config/config.yaml"]
    # depends_on:
    #   - db

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - 80:80
    networks:
      - webnet
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - martin

networks:
  webnet:

volumes:
  caddy_data:
  caddy_config: